### ISSUE TITLE
move project boards to org wide boards

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-spec#121]
so we can put sdk and spec related issues on the same board

**Comment by bridgetkromhout** [comment]
Reading https://help.github.com/en/github/managing-your-work-on-github/about-project-boards and I'm not sure _how_ to do this. It might require copying the boards instead of trying to import them.

Specifically, I am not seeing how to directly convert "Repository project boards" into "Organization-wide project boards".

**Comment by bridgetkromhout** [comment]
Resolution: it's possible to copy the structure of a repo-level board when creating an org-level board. I have done so in https://github.com/servicemeshinterface/smi-spec/projects and re-created all the items.
